# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xxKG8zmjFyWDMcrJ70moU4_gcRD8cJRN
"""

from flask import Flask, render_template, request, redirect, url_for, session
import os

app = Flask(__name__)
app.secret_key = 'your_secret_key'
UPLOAD_FOLDER = 'uploads'
os.makedirs(UPLOAD_FOLDER, exist_ok=True)
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/upload', methods=['POST'])
def upload():
    language = request.form.get('language')
    session['language'] = language
    return render_template('upload.html', language=language)

@app.route('/process', methods=['POST'])
def process():
    prompt = request.form['prompt']
    pdf_file = request.files['file']
    language = session.get('language')

    if not pdf_file:
        return "No file uploaded!", 400

    file_path = os.path.join(app.config['UPLOAD_FOLDER'], pdf_file.filename)
    pdf_file.save(file_path)
    session['file_path'] = file_path

    if language == 'english':
        from english import generate_questions_from_prompt_with_rag, extract_clean_text_chunks_from_pdf
        text_chunks = extract_clean_text_chunks_from_pdf(file_path)
        questions = generate_questions_from_prompt_with_rag(prompt, text_chunks)
    elif language == 'hindi':
        from hindi import process_hindi_pdf
        questions = process_hindi_pdf(prompt, file_path)
    elif language == 'sanskrit':
        from sanskrit import generate_questions_from_prompt_with_rag, extract_clean_text_chunks_from_pdf
        text_chunks = extract_clean_text_chunks_from_pdf(file_path)
        questions = generate_questions_from_prompt_with_rag(prompt, text_chunks)
    else:
        return "Invalid language selected.", 400

    return render_template('result.html', questions=questions)

if __name__ == '__main__':
    app.run(debug=True)